name: clasify_batik_bab7
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+9
  tflite_v2: ^1.0.0
  flutter_spinkit: ^5.1.0
  get: ^4.6.6  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
